from random import choice
from random import randint
from time import sleep
liste = ["tas","kagit","makas"]
a = 1
print("ig : songur_as")
print("github : songuras")
while a != 0 :
    print("Taş kağıt makas oyununa hoşgeldiniz bilgisayara karşı oynamak  için 1'i 2 kişi oynamak için  2'yi çıkış için 0'ı tuşlayın")
    secim  = int(input("seçiminiz"))
    if secim == 1 :
        print("1 = taş ")
        print("2 = kağıt")
        print("3 = makas")
        oyuncu_secim = int(input("seçiminiz :    "))
        pc_secim = choice(liste)
        sleep(1)
        if oyuncu_secim == 1 and pc_secim == "tas" :
            print("bilgisayarın secimi = taş")
            print("berabere")
        elif oyuncu_secim == 1 and pc_secim == "kagit" :
            print("bilgisayarın seçimi = kağıt")
            print("bilgisayar kazandı")
        elif oyuncu_secim == 1 and pc_secim == "makas" :
            print("bilgisayarın seçimi = makas ")
            print("kazandınız")
        elif oyuncu_secim == 2 and pc_secim == "kagit" :
            print("bilgisayarın seçimi = kağıt")
            print("berabere")
        elif oyuncu_secim == 2 and pc_secim == "tas":
            print("bilgisayarın secimi = taş")
            print("kazandınız")
        elif oyuncu_secim == 2 and pc_secim == "makas":
            print("bilgisayarın secimi = makas")
            print("bilgisayar kazandı")
        elif oyuncu_secim == 3 and pc_secim == "makas" :
            print("bilgisayarın seçimi = makas")
            print("berabere")
        elif oyuncu_secim == 3 and pc_secim == "tas" :
            print("bilgisayarın seçimi = taş")
            print("bilgisayar kazandı" )
        elif oyuncu_secim == 3 and pc_secim == "kagit" :
            print("bilgisayarın seçimi = kağıt")
            print("kazandınız")
        else :
            print("lütfen taş,kağıt veya makastan birini seçiniz")
    elif secim == 2 :
        birinci_isim = input("birinci oyuncu için kullanıcı adı : ")
        ikinci_isim = input("ikinci oyuncu için kullanıcı adı : ")
        sira = randint(1, 2)
        if sira == 1 :
            print(birinci_isim , "başlıyor")
            print("1 = taş ")
            print("2 = kağıt")
            print("3 = makas")
            print(birinci_isim,"için seçim")
            birinci_secim = int(input())
            print("seçim işleniyor .....")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(ikinci_isim,"için seçim")
            ikinci_secim = int(input())
            if birinci_secim == 1 and ikinci_secim == 1 :
                print("berabere")
            elif birinci_secim == 1 and ikinci_secim == 2 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 1 and ikinci_secim == 3 :
                print(birinci_isim,"kazandı")
            elif birinci_secim == 2 and ikinci_secim == 1 :
                print(birinci_isim,"kazandı")
            elif birinci_secim == 2 and ikinci_secim == 2 :
                print("berabere")
            elif birinci_secim == 2 and ikinci_secim ==3 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 3 and ikinci_secim == 1 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 3 and ikinci_secim == 2 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 3 and ikinci_secim == 3 :
                print("berabere")
            else :
                print("lütfen iki oyuncu için de seçeneklerden birini seçiniz")
        elif sira == 2 :
            print(ikinci_isim,"başlıyor")
            print("1 = taş ")
            print("2 = kağıt")
            print("3 = makas")
            print(ikinci_isim,"için seçim")
            ikinci_secim = int(input())
            print("seçim işleniyor .....")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(".")
            print(birinci_isim,"için seçim")
            birinci_secim = int(input())
            if birinci_secim == 1 and ikinci_secim == 1 :
                print("berabere")
            elif birinci_secim == 1 and ikinci_secim == 2 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 1 and ikinci_secim == 3 :
                print(birinci_isim,"kazandı")
            elif birinci_secim == 2 and ikinci_secim == 1 :
                print(birinci_isim,"kazandı")
            elif birinci_secim == 2 and ikinci_secim == 2 :
                print("berabere")
            elif birinci_secim == 2 and ikinci_secim ==3 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 3 and ikinci_secim == 1 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 3 and ikinci_secim == 2 :
                print(ikinci_isim,"kazandı")
            elif birinci_secim == 3 and ikinci_secim == 3 :
                print("berabere")
            else :
                print("lütfen iki oyuncu için de seçeneklerden birini seçiniz")
    elif secim == 0 :
        raise SystemExit
    else :
        print("lütfen menüden bir seçim yapınız")